### ISSUE TITLE
I need a static binary of awk for android

### ISSUE THREAD

**Issue by ghost** [e36freak/awk-libs#3]
Platform armv7

**Comment by rdebath** [comment]
Um, this repo is awk scripts not binaries.

How about trying [here](http://lmgtfy.com/?q=static+binary+of+awk+for+android+armv7)

Or busybox usually has a 'good enough' version of awk ie: `busybox awk ...`

**Comment by ghost** [comment]
```
Or busybox usually has a 'good enough' version of awk ie: busybox awk ...
```

Busybox I have it But in it awk does not know anything at all, there's a stripped down version and I'm very unhappy with it

**Comment by e36freak** [comment]
I don't see a standalone binary available, though I can't imagine it would be too ridiculous to compile one. Only thing I see that includes gawk 4 is "zshaolin", which is a zsh package

**Comment by rdebath** [comment]
Sigh, okay, No idea if this'll work; it's an mawk binary ARM7 static compiled on Linux. Gawk is often a bit of a pain to compile; this is easy.

If it works buy yourself a Raspberry PI and use Raspian to build your stuff.

https://gist.github.com/rdebath/b2e087c0af9593163bdd360170b08f16

**Comment by ghost** [comment]
> If it works buy yourself a Raspberry PI and use > Raspian to build your stuff.

This is not what I need in the archive is awk and not sed

**Comment by ghost** [comment]
> I don't see a standalone binary available, though I can't imagine it would be too ridiculous to compile one.
There is nothing funny there, this program is very useful for my firmware which I will collect that is which I already collect.

**Comment by e36freak** [comment]
OK, so at this point I have no idea what you want. I'm just gonna close this because it's getting nowhere and is completely irrelevant to the repository
